#
# Module manifest for module 'Storage.Linux'
#

@{
    RootModule        = 'Storage.Linux.psm1'
    ModuleVersion     = '0.6.0'
    GUID              = 'b2c3d4e5-f6a7-8901-bcde-f12345678901'
    Author            = 'Peppe Kerstens'
    CompanyName       = ''
    Copyright         = '(c) Peppe Kerstens. GPL-3.0 license.'
    Description       = 'PowerShell module for Linux providing cmdlet parity with the Windows Storage module. Wraps lsblk, df and sfdisk to implement Get-Disk, Get-PhysicalDisk, Get-Partition and Get-Volume. Remaining cmdlets emit a not-implemented warning.'
    PowerShellVersion = '7.2'
    RequiredModules   = @()

    FunctionsToExport = @(
        'Add-InitiatorIdToMaskingSet',
        'Add-PartitionAccessPath',
        'Add-PhysicalDisk',
        'Add-StorageFaultDomain',
        'Add-TargetPortToMaskingSet',
        'Add-VirtualDiskToMaskingSet',
        'Block-FileShareAccess',
        'Clear-Disk',
        'Clear-FileStorageTier',
        'Clear-StorageDiagnosticInfo',
        'Connect-VirtualDisk',
        'Convert-PhysicalDisk',
        'Debug-FileShare',
        'Debug-StorageSubSystem',
        'Debug-Volume',
        'Disable-PhysicalDiskIdentification',
        'Disable-StorageDataCollection',
        'Disable-StorageEnclosureIdentification',
        'Disable-StorageEnclosurePower',
        'Disable-StorageHighAvailability',
        'Disable-StorageMaintenanceMode',
        'Disconnect-VirtualDisk',
        'Dismount-DiskImage',
        'Enable-PhysicalDiskIdentification',
        'Enable-StorageDataCollection',
        'Enable-StorageEnclosureIdentification',
        'Enable-StorageEnclosurePower',
        'Enable-StorageHighAvailability',
        'Enable-StorageMaintenanceMode',
        'Format-Volume',
        'Get-DedupProperties',
        'Get-Disk',
        'Get-DiskImage',
        'Get-DiskStorageNodeView',
        'Get-FileIntegrity',
        'Get-FileShare',
        'Get-FileShareAccessControlEntry',
        'Get-FileStorageTier',
        'Get-InitiatorId',
        'Get-InitiatorPort',
        'Get-MaskingSet',
        'Get-OffloadDataTransferSetting',
        'Get-Partition',
        'Get-PartitionSupportedSize',
        'Get-PhysicalDisk',
        'Get-PhysicalDiskStorageNodeView',
        'Get-PhysicalExtent',
        'Get-PhysicalExtentAssociation',
        'Get-ResiliencySetting',
        'Get-StorageAdvancedProperty',
        'Get-StorageChassis',
        'Get-StorageDataCollection',
        'Get-StorageDiagnosticInfo',
        'Get-StorageEnclosure',
        'Get-StorageEnclosureStorageNodeView',
        'Get-StorageEnclosureVendorData',
        'Get-StorageExtendedStatus',
        'Get-StorageFaultDomain',
        'Get-StorageFileServer',
        'Get-StorageFirmwareInformation',
        'Get-StorageHealthAction',
        'Get-StorageHealthReport',
        'Get-StorageHealthSetting',
        'Get-StorageHistory',
        'Get-StorageJob',
        'Get-StorageNode',
        'Get-StoragePool',
        'Get-StorageProvider',
        'Get-StorageRack',
        'Get-StorageReliabilityCounter',
        'Get-StorageScaleUnit',
        'Get-StorageSetting',
        'Get-StorageSite',
        'Get-StorageSubSystem',
        'Get-StorageTier',
        'Get-StorageTierSupportedSize',
        'Get-SupportedClusterSizes',
        'Get-SupportedFileSystems',
        'Get-TargetPort',
        'Get-TargetPortal',
        'Get-VirtualDisk',
        'Get-VirtualDiskSupportedSize',
        'Get-Volume',
        'Get-VolumeCorruptionCount',
        'Get-VolumeScrubPolicy',
        'Grant-FileShareAccess',
        'Hide-VirtualDisk',
        'Initialize-Disk',
        'Mount-DiskImage',
        'New-FileShare',
        'New-MaskingSet',
        'New-Partition',
        'New-StorageFileServer',
        'New-StoragePool',
        'New-StorageSubsystemVirtualDisk',
        'New-StorageTier',
        'New-VirtualDisk',
        'New-VirtualDiskClone',
        'New-VirtualDiskSnapshot',
        'New-Volume',
        'Optimize-StoragePool',
        'Optimize-Volume',
        'Register-StorageSubsystem',
        'Remove-FileShare',
        'Remove-InitiatorId',
        'Remove-InitiatorIdFromMaskingSet',
        'Remove-MaskingSet',
        'Remove-Partition',
        'Remove-PartitionAccessPath',
        'Remove-PhysicalDisk',
        'Remove-StorageFaultDomain',
        'Remove-StorageFileServer',
        'Remove-StorageHealthIntent',
        'Remove-StorageHealthSetting',
        'Remove-StoragePool',
        'Remove-StorageTier',
        'Remove-TargetPortFromMaskingSet',
        'Remove-VirtualDisk',
        'Remove-VirtualDiskFromMaskingSet',
        'Rename-MaskingSet',
        'Repair-FileIntegrity',
        'Repair-VirtualDisk',
        'Repair-Volume',
        'Reset-PhysicalDisk',
        'Reset-StorageReliabilityCounter',
        'Resize-Partition',
        'Resize-StorageTier',
        'Resize-VirtualDisk',
        'Revoke-FileShareAccess',
        'Save-StorageDataCollection',
        'Set-Disk',
        'Set-FileIntegrity',
        'Set-FileShare',
        'Set-FileStorageTier',
        'Set-InitiatorPort',
        'Set-Partition',
        'Set-PhysicalDisk',
        'Set-ResiliencySetting',
        'Set-StorageFileServer',
        'Set-StorageHealthSetting',
        'Set-StoragePool',
        'Set-StorageProvider',
        'Set-StorageSetting',
        'Set-StorageSubSystem',
        'Set-StorageTier',
        'Set-VirtualDisk',
        'Set-Volume',
        'Set-VolumeScrubPolicy',
        'Show-StorageHistory',
        'Show-VirtualDisk',
        'Start-StorageDiagnosticLog',
        'Stop-StorageDiagnosticLog',
        'Stop-StorageJob',
        'Unblock-FileShareAccess',
        'Unregister-StorageSubsystem',
        'Update-Disk',
        'Update-HostStorageCache',
        'Update-StorageFirmware',
        'Update-StoragePool',
        'Update-StorageProviderCache',
        'Write-VolumeCache'
    )

    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @(
        'Disable-PhysicalDiskIndication',
        'Disable-StorageDiagnosticLog',
        'Enable-PhysicalDiskIndication',
        'Enable-StorageDiagnosticLog',
        'Flush-Volume',
        'Get-DiskSNV',
        'Get-PhysicalDiskSNV',
        'Get-StorageEnclosureSNV',
        'Initialize-Volume',
        'Write-FileSystemCache'
    )

    PrivateData = @{
        PSData = @{
            Tags         = @('Linux', 'Storage', 'Disk', 'Partition', 'Volume', 'CrossPlatform', 'lsblk')
            LicenseUri   = 'https://github.com/peppekerstens/Storage.Linux/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/peppekerstens/Storage.Linux'
            ReleaseNotes = @'
0.6.0 - Implemented Clear-Disk (wipefs), Dismount-DiskImage (losetup -d), Format-Volume (mkfs), Get-DiskImage (losetup -l --json), New-Partition (sfdisk --append), Remove-Partition (sfdisk --delete), Repair-Volume (fsck), Resize-Partition (sfdisk -N + resize2fs/xfs_growfs). All PSSA-clean.
0.3.0 - FunctionsToExport expanded to all 148 Windows Storage functions. AliasesToExport lists all 10 Windows Storage aliases. Get-LsBlk (Crescendo internal) removed from public surface.
0.2.0 - Get-Disk, Get-PhysicalDisk, Get-Partition, Get-Volume: full Linux implementations via lsblk/df. Module manifest and root module added.
0.1.0 - Initial scaffolding with proxy function stubs and Crescendo lsblk config.
'@
        }
    }
}
